name: pavilion
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  curved_navigation_bar: ^0.3.1
  flutter:
    sdk: flutter
  http: ^0.12.0+2
  shared_preferences: ^0.5.4+6
  fluttertoast: ^3.1.3
  flutter_slidable: ^0.5.3
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  
  assets:
    - assets/image/leftArrow.png
    - assets/image/profile.jpg
    - assets/image/avater.jpg

  uses-material-design: true

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/Poppins-Bold.ttf
        - asset: assets/Poppins-Regular.ttf
        - asset: assets/Poppins-Medium.ttf
          weight: 700

